version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      - chroma
      - playwright
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  playwright:
    image: node:20-slim
    command: npx -y @playwright/mcp@latest --host 0.0.0.0 --port 8931
    ports:
      - "8931:8931"

  chroma:
    image: chromadb/chroma
    ports:
      - "8001:8000" # Expose ChromaDB on host port 8001 to avoid conflict with backend
    volumes:
      - chroma_data:/chroma/.chroma/index

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - backend
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0

volumes:
  chroma_data:
